version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=anotherpassword
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8888
    volumes:
      - .:/quizshow
    ports:
      - "8888:8888"
    depends_on:
      - db